import { StyleSheet } from "react-native";

import { colors } from "./colors";
import { radius } from "./radius";
import { spacing } from "./spacing";
import { fonts } from "./typography";

export const shared = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  safeArea: {
    flex: 1,
  },
  card: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    backgroundColor: colors.surface,
    borderColor: colors.surfaceBorder,
    borderWidth: 1,
    borderRadius: radius.lg,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md,
  },
  cardIconCircle: {
    width: 48,
    height: 48,
    borderRadius: radius.xl,
    backgroundColor: colors.iconCircle,
    alignItems: "center",
    justifyContent: "center",
  },
  cardTextWrap: {
    gap: 2,
  },
  cardTitle: {
    fontFamily: fonts.semiBold,
    fontSize: 16,
    color: colors.textPrimary,
  },
  cardSubtitle: {
    fontFamily: fonts.regular,
    fontSize: 13,
    color: colors.textSecondary,
  },
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.divider,
  },
  dividerText: {
    marginHorizontal: 12,
    fontFamily: fonts.medium,
    fontSize: 13,
    letterSpacing: 1,
    color: colors.textSecondary,
  },
  outlineButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    borderWidth: 1.5,
    borderColor: colors.accent,
    borderRadius: radius.md,
    paddingVertical: 14,
  },
  outlineButtonText: {
    fontFamily: fonts.semiBold,
    fontSize: 15,
    color: colors.accent,
  },
  primaryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "stretch",
    gap: spacing.sm,
    backgroundColor: colors.buttonPrimary,
    borderRadius: radius.md,
    paddingVertical: 16,
  },
  primaryButtonText: {
    fontFamily: fonts.semiBold,
    fontSize: 17,
    color: colors.textPrimary,
  },
  input: {
    backgroundColor: colors.surface,
    borderColor: colors.surfaceBorder,
    borderWidth: 1,
    borderRadius: radius.md,
    paddingVertical: 16,
    paddingHorizontal: spacing.md,
    fontFamily: fonts.regular,
    fontSize: 17,
    color: colors.textPrimary,
  },
  title: {
    fontFamily: fonts.bold,
    fontSize: 30,
    color: colors.textPrimary,
  },
  subtitle: {
    fontFamily: fonts.regular,
    fontSize: 17,
    color: colors.textMuted,
    lineHeight: 24,
  },
  socialCircle: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: colors.iconCircle,
    alignItems: "center",
    justifyContent: "center",
  },
  footerText: {
    fontFamily: fonts.regular,
    fontSize: 16,
    color: colors.textMuted,
  },
  footerLink: {
    fontFamily: fonts.semiBold,
    fontSize: 16,
    color: colors.accent,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.surface,
    borderColor: colors.surfaceBorder,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  inputRow: {
    flexDirection: "row",
    gap: spacing.md,
  },
  checkboxBox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: colors.surfaceBorder,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxBoxChecked: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  termsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  termsText: {
    flex: 1,
    fontFamily: fonts.regular,
    fontSize: 14,
    lineHeight: 20,
    color: colors.textMuted,
  },
  termsLink: {
    fontFamily: fonts.semiBold,
    color: colors.accent,
  },
  shortDivider: {
    alignSelf: "center",
    width: 60,
    height: 1,
    backgroundColor: colors.divider,
  },
  sectionCard: {
    backgroundColor: colors.surface,
    borderColor: colors.surfaceBorder,
    borderWidth: 1,
    borderRadius: radius.lg,
    padding: spacing.md,
  },
  sectionTitle: {
    fontFamily: fonts.bold,
    fontSize: 19,
    color: colors.accent,
  },
  sectionSubtitle: {
    fontFamily: fonts.regular,
    fontSize: 14,
    color: colors.textMuted,
    marginTop: 4,
  },
  stepCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  stepCircleCompleted: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  stepCircleActive: {
    backgroundColor: colors.iconCircle,
    borderColor: colors.accent,
  },
  stepCircleUpcoming: {
    backgroundColor: colors.surface,
    borderColor: colors.surfaceBorder,
  },
  stepNumber: {
    fontFamily: fonts.bold,
    fontSize: 16,
    color: colors.textPrimary,
  },
  stepNumberMuted: {
    color: colors.textSecondary,
  },
  stepLabel: {
    width: 84,
    fontFamily: fonts.medium,
    fontSize: 12,
    color: colors.textPrimary,
    marginTop: 6,
    textAlign: "center",
  },
  stepLabelMuted: {
    color: colors.textSecondary,
  },
  stepLine: {
    flex: 1,
    height: 2,
    backgroundColor: colors.divider,
    marginTop: 21,
  },
  stepLineActive: {
    backgroundColor: colors.accent,
  },
  documentIconBox: {
    width: 44,
    height: 44,
    borderRadius: radius.sm,
    backgroundColor: colors.surface,
    borderColor: colors.surfaceBorder,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  addButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderColor: colors.accent,
    borderWidth: 1.5,
    borderRadius: radius.pill,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  addButtonText: {
    fontFamily: fonts.semiBold,
    fontSize: 13,
    color: colors.accent,
  },
  secondaryButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surface,
    borderColor: colors.surfaceBorder,
    borderWidth: 1,
    borderRadius: radius.md,
    paddingVertical: 16,
  },
  secondaryButtonText: {
    fontFamily: fonts.semiBold,
    fontSize: 15,
    color: colors.textPrimary,
  },
  navRow: {
    flexDirection: "row",
    gap: spacing.md,
  },
  dotsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.surfaceBorder,
  },
  dotActive: {
    width: 20,
    backgroundColor: colors.accent,
  },
});
